### ISSUE TITLE
Displaying the Turtle Image

### ISSUE THREAD

**Issue by PianoMan7** [Pixelguru26/Java-Turtle#2]
Hello, 

Is there an easy way or available method to display the PNG of the Turtle on the screen? It would be much easier to tell its current heading by being able to see this.

Thanks!

**Comment by Pixelguru26** [comment]
Hello!

The turtle image should already be displayed at every turtle's position with the appropriate heading. It is admittedly rather small, however if you aren't seeing it that's a bug, not a missing feature.
Nevertheless, I will look into adding a function to draw a provided PNG at the turtle's position, though this will be a permanent render like any other turtle draw function.
Let me know if the problem persists in a template project (as defined by the readme) or if there are other incompatibilities with your setup.
